# Copyright (c) 2012, Google Inc

name:         webframe
version:      0.1.0
author:       Ali Afshar <afshar@google.com>
description:  Web framework for dart.
homepage:     https://github.com/aliafshar/dart-webframe
dependencies:
  unittest: any
  logging: any
  signals:
    git: git://github.com/aliafshar/dart-signals.git
  routing:
    git: git://github.com/aliafshar/dart-routing.git
  roundtrip:
    git: git://github.com/aliafshar/dart-roundtrip.git
  extensions:
    git: git://github.com/aliafshar/dart-extensions.git
